package com.ddb.dao;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="TwtrSearchItems")
public class TwtrSearchItem {
	
	private String searchId;
	private Date reqTS;
	private String searchKey;
	private String reqUsr;
	private String searchType;
	private boolean isAvailable;
	private String lastStatus;
	private Date lastActyTS;
	private String lastDesc;
	private String lastPrcsName;
	private List<ActivityItem> activity;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getSearchId() {
		return searchId;
	}
	public void setSearchId(String searchId) {
		this.searchId = searchId;
	}
	
	@DynamoDBRangeKey
	public Date getReqTS() {
		return reqTS;
	}
	public void setReqTS(Date reqTS) {
		this.reqTS = reqTS;
	}
	
	public String getSearchKey() {
		return searchKey;
	}
	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}
	public String getReqUsr() {
		return reqUsr;
	}
	public void setReqUsr(String reqUsr) {
		this.reqUsr = reqUsr;
	}
	public String getSearchType() {
		return searchType;
	}
	public void setSearchType(String searchType) {
		this.searchType = searchType;
	}
	public boolean isAvailable() {
		return isAvailable;
	}
	public void setAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="TwtrSearch_Activity_GSI")
	public String getLastStatus() {
		return lastStatus;
	}
	public void setLastStatus(String lastStatus) {
		this.lastStatus = lastStatus;
	}
	
	@DynamoDBIndexRangeKey(globalSecondaryIndexName="TwtrSearch_Activity_GSI")
	public Date getLastActyTS() {
		return lastActyTS;
	}
	public void setLastActyTS(Date lastActyTS) {
		this.lastActyTS = lastActyTS;
	}
	public String getLastDesc() {
		return lastDesc;
	}
	public void setLastDesc(String lastDesc) {
		this.lastDesc = lastDesc;
	}
	public String getLastPrcsName() {
		return lastPrcsName;
	}
	public void setLastPrcsName(String lastPrcsName) {
		this.lastPrcsName = lastPrcsName;
	}
	public List<ActivityItem> getActivity() {
		return activity;
	}
	public void setActivity(List<ActivityItem> activity) {
		this.activity = activity;
	}
	@Override
	public String toString() {
		return "TwtrSearchItem [searchId=" + searchId + ", reqTS=" + reqTS + ", searchKey=" + searchKey + ", reqUsr="
				+ reqUsr + ", searchType=" + searchType + ", isAvailable=" + isAvailable + ", lastStatus=" + lastStatus
				+ ", lastActyTS=" + lastActyTS + ", lastDesc=" + lastDesc + ", lastPrcsName=" + lastPrcsName
				+ ", activity=" + activity + "]";
	}
	
	
	
	
	
	
}
